const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
async function api(path,options={}){const r=await fetch('/api/portal'+path,{credentials:'same-origin',cache:'no-store',headers:{'content-type':'application/json'},...options});if(!(r.headers.get('content-type')||'').includes('application/json'))throw new Error('Backend API is not active.');let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'هەڵەیەک ڕوویدا');return d}
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const message=(text,ok=true)=>{const m=$('#adminMessage');m.className='msg '+(ok?'ok':'');m.textContent=text};
async function loadApplications(){const d=await api('/admin/applications'),apps=d.applications||[];$('#pendingCount').textContent=apps.filter(x=>x.status==='pending').length;$('#applications').innerHTML=apps.map(a=>`<article class="app-card"><span class="badge">${esc(a.status)}</span><h3>${esc(a.full_name)}</h3><p>📞 <bdi dir="ltr">${esc(a.phone)}</bdi><br>🏪 ${esc(a.business||'—')}<br>📍 ${esc(a.city||'—')}<br>👤 ${esc(a.username)}<br>🗓 ${esc(a.created_at)}</p><div class="actions">${a.status!=='approved'?`<button class="approve" data-action="approve" data-id="${a.id}">پەسەندکردن</button>`:`<button class="reject" data-action="disable" data-id="${a.id}">ناچالاککردن</button>`}${a.status==='pending'?`<button class="reject" data-action="reject" data-id="${a.id}">ڕەتکردنەوە</button>`:''}</div></article>`).join('')||'<p>هیچ داواکارییەک نییە.</p>';$$('[data-action]').forEach(b=>b.onclick=()=>updateApplication(b.dataset.id,b.dataset.action))}
async function updateApplication(id,action){try{await api('/admin/applications',{method:'POST',body:JSON.stringify({id:Number(id),action})});message('گۆڕانکاری پاشەکەوت کرا.');loadApplications()}catch(e){message(e.message,false)}}
async function loadPrices(){const d=await api('/admin/products');$('#priceRows').innerHTML=(d.products||[]).map(p=>`<tr><td><select data-type="${p.id}">${['panel','inverter','battery','service'].map(x=>`<option value="${x}" ${p.type===x?'selected':''}>${x}</option>`).join('')}</select></td><td><input value="${esc(p.name)}" data-name="${p.id}"><input value="${esc(p.spec||'')}" data-spec="${p.id}" placeholder="مواصفات"></td><td><input type="number" value="${p.retail_price}" data-retail="${p.id}"></td><td><input type="number" value="${p.trade_price}" data-trade="${p.id}"></td><td><input type="number" value="${p.sort_order||0}" data-sort="${p.id}"></td><td><input class="check" type="checkbox" ${p.active?'checked':''} data-active="${p.id}"></td><td><button data-save-product="${p.id}">پاشەکەوت</button> <button class="reject" data-delete-product="${p.id}">سڕینەوە</button></td></tr>`).join('');$$('[data-save-product]').forEach(b=>b.onclick=()=>saveProduct(b.dataset.saveProduct));$$('[data-delete-product]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.deleteProduct))}
async function saveProduct(id){try{await api('/admin/products',{method:'POST',body:JSON.stringify({id:+id,type:$(`[data-type="${id}"]`).value,name:$(`[data-name="${id}"]`).value,spec:$(`[data-spec="${id}"]`).value,retailPrice:+$(`[data-retail="${id}"]`).value,tradePrice:+$(`[data-trade="${id}"]`).value,sortOrder:+$(`[data-sort="${id}"]`).value,active:$(`[data-active="${id}"]`).checked})});message('بابەتەکە پاشەکەوت کرا.');loadPrices()}catch(e){message(e.message,false)}}
async function deleteProduct(id){if(!confirm('دڵنیایت؟'))return;try{await api('/admin/products',{method:'DELETE',body:JSON.stringify({id:+id})});message('سڕایەوە.');loadPrices()}catch(e){message(e.message,false)}}
$('#addProductForm').onsubmit=async e=>{e.preventDefault();try{await api('/admin/products',{method:'POST',body:JSON.stringify({type:$('#newType').value,name:$('#newName').value,spec:$('#newSpec').value,retailPrice:+$('#newRetail').value,tradePrice:+$('#newTrade').value,sortOrder:+$('#newSort').value,active:true})});e.target.reset();message('بابەتی نوێ زیاد کرا.');loadPrices()}catch(x){message(x.message,false)}};
const serviceLabels={structurePerPanel:'ستراکچەری هەر پانێڵ',installationPerPanel:'دامەزراندنی هەر پانێڵ',solarCablePerMeter:'کێبڵی خۆر / مەتر',acCablePerMeter:'کێبڵی AC / مەتر',dcProtectionSingle:'DC Protection ـ یەک فەیز',dcProtection3ph:'DC Protection ـ سێ فەیز',acProtectionSingle:'AC Protection ـ یەک فەیز',acProtection3ph:'AC Protection ـ سێ فەیز',transportErbil:'گواستنەوەی هەولێر',transportOutside:'گواستنەوەی دەرەوەی هەولێر',otherElectricalUpTo16:'کاری کارەبایی تا ١٦ پانێڵ',otherElectricalAbove16:'کاری کارەبایی زیاتر لە ١٦ پانێڵ',batteryBusbarMinimum:'کەمترین باتری بۆ Busbar',batteryBusbarPrice:'نرخی Battery Busbar'};
let calcItems=[];
async function loadCalculator(){const d=await api('/admin/calculator');calcItems=d.items||[];$('#serviceFields').innerHTML=Object.entries(serviceLabels).map(([k,l])=>`<label>${l}<input type="number" min="0" step=".01" data-setting="${k}" value="${d.settings[k]??0}"></label>`).join('');renderCalculatorItems()}
function itemPayload(prefix,id=0){return {id,category:$(`#${prefix}Category`)?.value||$(`[data-field="category"][data-id="${id}"]`).value,quality:$(`#${prefix}Quality`)?.value||$(`[data-field="quality"][data-id="${id}"]`).value,mode:$(`#${prefix}Mode`)?.value||$(`[data-field="mode"][data-id="${id}"]`).value,name:$(`#${prefix}Name`)?.value||$(`[data-field="name"][data-id="${id}"]`).value,code:$(`#${prefix}Code`)?.value||$(`[data-field="code"][data-id="${id}"]`).value,price:+($(`#${prefix}Price`)?.value??$(`[data-field="price"][data-id="${id}"]`).value),warranty:$(`#${prefix}Warranty`)?.value||$(`[data-field="warranty"][data-id="${id}"]`).value,watts:+($(`#${prefix}Watts`)?.value??$(`[data-field="watts"][data-id="${id}"]`).value),kw:+($(`#${prefix}Kw`)?.value??$(`[data-field="kw"][data-id="${id}"]`).value),phase:$(`#${prefix}Phase`)?.value||$(`[data-field="phase"][data-id="${id}"]`).value,maxPanels:+($(`#${prefix}MaxPanels`)?.value??$(`[data-field="max_panels"][data-id="${id}"]`).value),ampsPerHour:+($(`#${prefix}Amps`)?.value??$(`[data-field="amps_per_hour"][data-id="${id}"]`).value),sortOrder:+($(`#${prefix}Sort`)?.value??$(`[data-field="sort_order"][data-id="${id}"]`).value),active:id?$(`[data-field="active"][data-id="${id}"]`).checked:true}}
function select(field,id,value,opts){return `<select data-field="${field}" data-id="${id}">${opts.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select>`}
function renderCalculatorItems(){const filter=$('#calcFilter').value,items=calcItems.filter(x=>filter==='all'||x.category===filter);$('#calcCount').textContent=`${items.length} بابەت`;$('#calculatorItems').innerHTML=items.map(x=>`<article class="catalog-card"><div class="catalog-head"><b>${esc(x.name)}</b><span>${x.category}</span></div><div class="form-grid calc-grid">${select('category',x.id,x.category,[['panel','پانێڵ'],['inverter','ئینڤێرتەر'],['battery','باتری']])}${select('quality',x.id,x.quality,[['high','بەرز'],['medium','ناوەند'],['standard','ئاسایی'],['common','هاوبەش']])}${select('mode',x.id,x.mode,[['both','هەردووکیان'],['easy','Easy'],['advanced','Advanced']])}<label>ناو<input data-field="name" data-id="${x.id}" value="${esc(x.name)}"></label><label>کۆد<input dir="ltr" data-field="code" data-id="${x.id}" value="${esc(x.code)}"></label><label>نرخ<input type="number" data-field="price" data-id="${x.id}" value="${x.price}"></label><label>گەرەنتی<input data-field="warranty" data-id="${x.id}" value="${esc(x.warranty)}"></label><label>وات<input type="number" data-field="watts" data-id="${x.id}" value="${x.watts}"></label><label>kW<input type="number" step=".1" data-field="kw" data-id="${x.id}" value="${x.kw}"></label>${select('phase',x.id,x.phase,[['single','Single Phase'],['3ph','3 Phase']])}<label>Max Panels<input type="number" data-field="max_panels" data-id="${x.id}" value="${x.max_panels}"></label><label>Amps/Hour<input type="number" data-field="amps_per_hour" data-id="${x.id}" value="${x.amps_per_hour}"></label><label>ڕیز<input type="number" data-field="sort_order" data-id="${x.id}" value="${x.sort_order}"></label><label class="active-label">چالاک<input class="check" type="checkbox" data-field="active" data-id="${x.id}" ${x.active?'checked':''}></label></div><div class="actions"><button data-save-calc="${x.id}">پاشەکەوت</button><button class="reject" data-delete-calc="${x.id}">سڕینەوە</button></div></article>`).join('');$$('[data-save-calc]').forEach(b=>b.onclick=()=>saveCalcItem(+b.dataset.saveCalc));$$('[data-delete-calc]').forEach(b=>b.onclick=()=>deleteCalcItem(+b.dataset.deleteCalc))}
async function saveCalcItem(id){const button=$(`[data-save-calc="${id}"]`),old=button?.textContent,payload=itemPayload('',id);if(button){button.disabled=true;button.textContent='پاشەکەوت دەکرێت...'}try{await api('/admin/calculator/item',{method:'POST',body:JSON.stringify(payload)});const index=calcItems.findIndex(x=>Number(x.id)===Number(id));if(index!==-1)calcItems[index]={...calcItems[index],category:payload.category,quality:payload.quality,mode:payload.mode,name:payload.name,code:payload.code,price:payload.price,warranty:payload.warranty,watts:payload.watts,kw:payload.kw,phase:payload.phase,max_panels:payload.maxPanels,amps_per_hour:payload.ampsPerHour,sort_order:payload.sortOrder,active:payload.active?1:0};renderCalculatorItems();message('گۆڕانکارییەکە پاشەکەوت کرا؛ دەتوانیت بەبێ Refresh دەستکاریی دیکە بکەیت.')}catch(e){message(e.message,false);if(button){button.disabled=false;button.textContent=old}}}
async function deleteCalcItem(id){if(!confirm('ئەم بابەتە لە کەلکولەیتەر بسڕدرێتەوە؟'))return;try{await api('/admin/calculator/item',{method:'DELETE',body:JSON.stringify({id})});message('بابەتەکە سڕایەوە.');loadCalculator()}catch(e){message(e.message,false)}}
$('#addCalcForm').onsubmit=async e=>{e.preventDefault();try{await api('/admin/calculator/item',{method:'POST',body:JSON.stringify(itemPayload('calc'))});e.target.reset();message('بابەتی نوێ زیاد کرا.');loadCalculator()}catch(x){message(x.message,false)}};
$('#saveServices').onclick=async()=>{const button=$('#saveServices'),old=button.textContent,settings={};$('[data-setting]').forEach(x=>settings[x.dataset.setting]=+x.value);button.disabled=true;button.textContent='پاشەکەوت دەکرێت...';try{await api('/admin/calculator/settings',{method:'POST',body:JSON.stringify({settings})});button.disabled=false;button.textContent=old;message('هەموو نرخەکان پاشەکەوت کران؛ پێویست بە Refresh نییە.')}catch(e){message(e.message,false);button.disabled=false;button.textContent=old}};
$('#calcFilter').onchange=renderCalculatorItems;
function showPanel(){$('#adminLogin').classList.add('hidden');$('#adminPanel').classList.remove('hidden');loadApplications();loadPrices();loadCalculator()}
$('#adminLoginForm').onsubmit=async e=>{e.preventDefault();try{await api('/admin/login',{method:'POST',body:JSON.stringify({username:$('#adminUsername').value,password:$('#adminPassword').value})});showPanel()}catch(x){$('#adminLoginError').textContent=x.message}};
$('#adminLogout').onclick=async()=>{await api('/admin/logout',{method:'POST'});location.reload()};
$$('nav [data-view]').forEach(b=>b.onclick=()=>{$$('nav [data-view]').forEach(x=>x.classList.toggle('active',x===b));['applications','prices','calculator'].forEach(v=>$(`#${v}View`).classList.toggle('hidden',b.dataset.view!==v))});
api('/admin/me').then(showPanel).catch(()=>{});
