const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const rewardsCss=document.createElement('link');rewardsCss.rel='stylesheet';rewardsCss.href='admin-rewards.css?v=1';document.head.appendChild(rewardsCss);
async function api(path,options={}){const r=await fetch('/api/portal'+path,{credentials:'same-origin',cache:'no-store',headers:{'content-type':'application/json'},...options});if(!(r.headers.get('content-type')||'').includes('application/json'))throw new Error('Backend API is not active.');let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'هەڵەیەک ڕوویدا');return d}
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const message=(text,ok=true)=>{const m=$('#adminMessage');m.className='msg '+(ok?'ok':'');m.textContent=text};
let installerApplications=[];
let installerStatus="pending";
function whatsappNumber(phone){let n=String(phone||'').replace(/\D/g,'');if(n.startsWith('00'))n=n.slice(2);if(n.startsWith('0'))n='964'+n.slice(1);if(!n.startsWith('964'))n='964'+n;return n}
function sendApprovalWhatsApp(id){const a=installerApplications.find(x=>String(x.id)===String(id));if(!a)return message('زانیاریی وەستاکە نەدۆزرایەوە.',false);const phone=whatsappNumber(a.phone);if(phone.length<10)return message('ژمارەی مۆبایلی وەستاکە دروست نییە.',false);const text=`بەڕێز وەستا ${a.full_name}، پیرۆزە 🎉\n\nئەکاونتەکەت لە وێبسایتی Alo Solar Energy چالاک کرا.\nئێستا دەتوانیت سەردانی ئەکاونتەکەت بکەیت و نرخە نایاب و تایبەتەکانی وەستاکان ببینیت.\n\n🔗 https://alosolarenergy.com/installers.html\n\nAlo Solar Energy\n📞 0776 440 0440`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}
function showInstallerQr(id){const a=installerApplications.find(x=>String(x.id)===String(id));if(!a?.verification_code)return message('کۆدی QR بەردەست نییە؛ پەڕەکە دووبارە بکەرەوە.',false);const verifyUrl=`https://alosolarenergy.com/verify-installer.html?code=${encodeURIComponent(a.verification_code)}`,imageUrl=`https://api.qrserver.com/v1/create-qr-code/?size=600x600&ecc=H&margin=12&data=${encodeURIComponent(verifyUrl)}`;$('#qrInstallerName').textContent=a.full_name;$('#qrImage').src=imageUrl;$('#openQrImage').href=imageUrl;$('#qrDialog').showModal()}
async function loadApplications(){
 const d=await api('/admin/applications'),apps=d.applications||[];installerApplications=apps;$('#pendingCount').textContent=apps.filter(x=>x.status==='pending').length;
 $('#applications').innerHTML=apps.map(a=>{const total=Number(a.reward_total||0),progress=Math.min(100,total/10000*100),reward=total>=10000?total*.02:0;return `<article class="app-card"><span class="badge">${esc(accountStatus(a))}</span><h3>${esc(a.full_name)}</h3><p>📞 <bdi dir="ltr">${esc(a.phone)}</bdi><br>🏪 ${esc(a.business||'—')}<br>📍 ${esc(a.city||'—')}<br>👤 ${esc(a.username)}<br>🗓 ${esc(a.created_at)}</p>${a.status==='approved'?`<div class="installer-tools"><button class="approval-whatsapp" data-approval-whatsapp="${a.id}">نامەی چالاککردن لە WhatsApp</button><button class="qr-button" data-installer-qr="${a.id}">QR ـی وەستا</button></div><section class="purchase-admin"><div class="purchase-head"><b>کڕینی دوو مانگی کۆتایی</b><strong>$${total.toLocaleString('en-US',{maximumFractionDigits:2})}</strong></div><progress class="purchase-track" value="${progress}" max="100"></progress><small>${progress.toFixed(1)}% لە $10,000${reward?` · Cashback: $${reward.toFixed(2)}`:''}</small><div class="purchase-form"><input type="number" min="0.01" step="0.01" placeholder="بڕی کڕین ($)" data-purchase-amount="${a.id}"><input type="text" maxlength="60" placeholder="ژمارەی پسووڵە" data-purchase-invoice="${a.id}"><input type="date" data-purchase-date="${a.id}"><input type="text" maxlength="180" placeholder="تێبینی" data-purchase-note="${a.id}"><button data-add-purchase="${a.id}">تۆمارکردنی کڕین</button><button class="purchase-history-button" data-purchase-history="${a.id}">مێژوو</button></div><div class="purchase-history hidden" data-history-list="${a.id}"></div></section><div class="password-reset"><label>پاسوۆردی نوێ<input type="password" minlength="8" autocomplete="new-password" dir="ltr" placeholder="لانیکەم ٨ پیت" data-reset-input="${a.id}"></label><button class="reset-password-button" data-reset-password="${a.id}">گۆڕینی پاسوۆرد</button></div>`:''}${a.ban_reason?`<p class="account-reason">هۆکاری باند: ${esc(a.ban_reason)}</p>`:''}${a.status!=='approved'&&Number(a.purchase_count)>0?`<button class="purchase-history-button" data-purchase-history="${a.id}">مێژووی کڕین</button><div class="purchase-history hidden" data-history-list="${a.id}"></div>`:''}<div class="actions">${accountActions(a)}</div></article>`}).join('')||'<p>هیچ داواکارییەک نییە.</p>';
 $$('[data-action]').forEach(b=>b.onclick=()=>updateApplication(b.dataset.id,b.dataset.action));$$('[data-approval-whatsapp]').forEach(b=>b.onclick=()=>sendApprovalWhatsApp(b.dataset.approvalWhatsapp));$$('[data-installer-qr]').forEach(b=>b.onclick=()=>showInstallerQr(b.dataset.installerQr));$$('[data-reset-password]').forEach(b=>b.onclick=()=>resetInstallerPassword(b.dataset.resetPassword));$$('[data-add-purchase]').forEach(b=>b.onclick=()=>addPurchase(b.dataset.addPurchase));$$('[data-purchase-history]').forEach(b=>b.onclick=()=>loadPurchaseHistory(b.dataset.purchaseHistory));
 for(const [group,id] of [["pending","countPending"],["approved","countApproved"],["other","countOther"]])$("#"+id).textContent=apps.filter(a=>(a.archived_at?"other":["pending","approved"].includes(a.status)?a.status:"other")===group).length;
 filterApplications();
}
function normalizeInstallerSearch(value){return String(value??'').normalize('NFKC').toLowerCase().replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776)).replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/[\u064b-\u065f\u0640\u200c-\u200f]/g,'').trim()}
function matchesInstallerSearch(a,query){const fields=[a.full_name,a.phone,a.username,a.business,a.city,`ALO-${String(a.id).padStart(6,'0')}`].map(normalizeInstallerSearch);const phone=normalizeInstallerSearch(a.phone).replace(/[^0-9]/g,'');return normalizeInstallerSearch(query).split(/\s+/).filter(Boolean).every(term=>fields.some(f=>f.includes(term))||(/^\+?[0-9()-]+$/.test(term)&&phone.includes(term.replace(/[^0-9]/g,''))))}
function filterApplications(){const query=$('#applicationSearch').value;let count=0;$$('#applications > .app-card').forEach((card,index)=>{const a=installerApplications[index],group=a.archived_at?"other":["pending","approved"].includes(a.status)?a.status:"other";const match=group===installerStatus&&matchesInstallerSearch(a,query);card.classList.toggle('hidden',!match);if(match)count++});$('#applicationSearchCount').textContent=`${count} لە ${installerApplications.length} وەستا` ;$('#applicationSearchEmpty').classList.toggle('hidden',count>0||installerApplications.length===0)}
$('#applicationSearch').addEventListener('input',filterApplications);
$('#clearApplicationSearch').addEventListener('click',()=>{$('#applicationSearch').value='';filterApplications();$('#applicationSearch').focus()});
async function addPurchase(id){const amount=+$(`[data-purchase-amount="${id}"]`).value,invoiceNumber=$(`[data-purchase-invoice="${id}"]`).value,purchasedAt=$(`[data-purchase-date="${id}"]`).value,note=$(`[data-purchase-note="${id}"]`).value;if(!amount||amount<=0)return message('تکایە بڕی کڕین بە دروستی بنووسە.',false);try{await api('/admin/purchases',{method:'POST',body:JSON.stringify({installerId:+id,amount,invoiceNumber,purchasedAt,note})});message('کڕینەکە تۆمار کرا و Cashback نوێ کرایەوە.');await loadApplications()}catch(e){message(e.message,false)}}
async function loadPurchaseHistory(id){const box=$(`[data-history-list="${id}"]`);if(!box)return;try{const d=await api(`/admin/purchases?installerId=${encodeURIComponent(id)}`),rows=d.purchases||[];box.innerHTML=rows.length?rows.map(x=>`<div class="purchase-row"><span><b>$${Number(x.amount).toLocaleString('en-US',{maximumFractionDigits:2})}</b><small>${esc(x.invoice_number||'بێ ژمارەی پسووڵە')} · ${esc(x.purchased_at)}</small><em>${esc(x.note||'')}</em></span><button data-delete-purchase="${x.id}">×</button></div>`).join(''):'<p>هێشتا هیچ کڕینێک تۆمار نەکراوە.</p>';box.classList.remove('hidden');$$('[data-delete-purchase]').forEach(b=>b.onclick=()=>deletePurchase(b.dataset.deletePurchase,id))}catch(e){message(e.message,false)}}
async function deletePurchase(purchaseId,installerId){if(!confirm('دڵنیایت لە سڕینەوەی ئەم کڕینە؟'))return;try{await api('/admin/purchases',{method:'DELETE',body:JSON.stringify({id:+purchaseId})});message('کڕینەکە سڕایەوە.');await loadApplications();await loadPurchaseHistory(installerId)}catch(e){message(e.message,false)}}
function accountStatus(a){return a.archived_at?'ئەرشیفکراو':({approved:'چالاک',pending:'چاوەڕوانی پەسەندکردن',rejected:'ڕەتکراوە',disabled:'باندکراو'}[a.status]||a.status)}
function accountActions(a){
 const button=(action,label,kind='reject')=>`<button class="${kind}" data-action="${action}" data-id="${a.id}">${label}</button>`;
 if(a.archived_at)return button('restore','گەڕاندنەوە بۆ پەسەندکردن','approve');
 let html=a.status==='disabled'?button('unban','لابردنی باند','approve'):a.status==='approved'?button('ban','باندکردن'):button('approve','پەسەندکردن','approve')+button('ban','باندکردن');
 if(a.status==='pending')html+=button('reject','ڕەتکردنەوە');
 return html+(Number(a.purchase_count)>0?button('archive','ئەرشیفکردن'):button('delete','سڕینەوەی هەمیشەیی','delete-account'));
}
async function updateApplication(id,action){
 const a=installerApplications.find(x=>String(x.id)===String(id));if(!a)return;
 let confirmation,reason;
 if(action==='delete'){
  confirmation=prompt(`سڕینەوەی هەمیشەیی ئەکاونتی ${a.full_name}. ئەم کردارە ناگەڕێتەوە. بۆ پشتڕاستکردنەوە بنووسە: ${a.username}`);
  if(confirmation===null)return;if(confirmation!==a.username)return message('ناوی بەکارهێنەر یەک ناگرێتەوە.',false);
 }else if(action==='ban'){
  reason=prompt(`باندکردنی ${a.full_name}: دەستگەیشتن بە نرخەکان و QR ڕادەگیرێت. هۆکار بنووسە (ئارەزوومەندانە):`);if(reason===null)return;
 }else if(!confirm(`${a.full_name}: ${action==='archive'?'ئەکاونتەکە ئەرشیف بکرێت؟ تۆمارەکانی کڕین دەمێننەوە.':action==='restore'?'بگەڕێتەوە بۆ چاوەڕوانی پەسەندکردن؟':action==='unban'?'باند لاببرێت و ئەکاونتەکە چالاک بکرێت؟':'گۆڕانکارییەکە پشتڕاست دەکەیتەوە؟'}`))return;
 const buttons=[...$$(`[data-action][data-id="${id}"]`)];buttons.forEach(b=>b.disabled=true);
 try{await api('/admin/applications',{method:'POST',body:JSON.stringify({id:Number(id),action,confirmation,reason})});await loadApplications();message(action==='delete'?'ئەکاونتەکە سڕایەوە.':action==='archive'?'ئەکاونتەکە ئەرشیف کرا؛ تۆمارەکانی کڕین پارێزران.':'گۆڕانکاری پاشەکەوت کرا.')}catch(e){message(e.message,false)}finally{buttons.forEach(b=>b.disabled=false)}
}
async function resetInstallerPassword(id){const input=$(`[data-reset-input="${id}"]`),button=$(`[data-reset-password="${id}"]`),password=input.value;if(password.length<8){message('پاسوۆردە نوێیەکە دەبێت لانیکەم ٨ پیت بێت.',false);input.focus();return}if(!confirm('دڵنیایت دەتەوێت پاسوۆردی ئەم وەستایە بگۆڕیت؟'))return;const old=button.textContent;button.disabled=true;button.textContent='پاشەکەوت دەکرێت...';try{await api('/admin/reset-password',{method:'POST',body:JSON.stringify({id:Number(id),password})});input.value='';message('پاسوۆردی نوێ پاشەکەوت کرا. ئێستا بە شێوەیەکی پارێزراو بۆ وەستاکەی بنێرە.')}catch(e){message(e.message,false)}finally{button.disabled=false;button.textContent=old}}
const installerTypes=[['panel','پانێڵ'],['inverter','ئینڤێرتەر'],['battery','باتری'],['electrical','کارەبا'],['structure','ستراکچەر'],['cable','کێبڵ']];
async function loadPrices(){const d=await api('/admin/products');$('#priceRows').innerHTML=(d.products||[]).map(p=>`<tr><td><select data-type="${p.id}">${installerTypes.map(([x,label])=>`<option value="${x}" ${p.type===x?'selected':''}>${label}</option>`).join('')}</select></td><td><input value="${esc(p.name)}" data-name="${p.id}"><input value="${esc(p.spec||'')}" data-spec="${p.id}" placeholder="مواصفات"></td><td><input type="number" value="${p.retail_price}" data-retail="${p.id}"></td><td><input type="number" value="${p.trade_price}" data-trade="${p.id}"></td><td><input type="number" value="${p.sort_order||0}" data-sort="${p.id}"></td><td><input class="check" type="checkbox" ${p.active?'checked':''} data-active="${p.id}"></td><td><button data-save-product="${p.id}">پاشەکەوت</button> <button class="reject" data-delete-product="${p.id}">سڕینەوە</button></td></tr>`).join('');$$('[data-save-product]').forEach(b=>b.onclick=()=>saveProduct(b.dataset.saveProduct));$$('[data-delete-product]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.deleteProduct))}
async function saveProduct(id){try{await api('/admin/products',{method:'POST',body:JSON.stringify({id:+id,type:$(`[data-type="${id}"]`).value,name:$(`[data-name="${id}"]`).value,spec:$(`[data-spec="${id}"]`).value,retailPrice:+$(`[data-retail="${id}"]`).value,tradePrice:+$(`[data-trade="${id}"]`).value,sortOrder:+$(`[data-sort="${id}"]`).value,active:$(`[data-active="${id}"]`).checked})});message('بابەتەکە پاشەکەوت کرا.');loadPrices()}catch(e){message(e.message,false)}}
async function deleteProduct(id){if(!confirm('دڵنیایت؟'))return;try{await api('/admin/products',{method:'DELETE',body:JSON.stringify({id:+id})});message('سڕایەوە.');loadPrices()}catch(e){message(e.message,false)}}
$('#addProductForm').onsubmit=async e=>{e.preventDefault();try{await api('/admin/products',{method:'POST',body:JSON.stringify({type:$('#newType').value,name:$('#newName').value,spec:$('#newSpec').value,retailPrice:+$('#newRetail').value,tradePrice:+$('#newTrade').value,sortOrder:+$('#newSort').value,active:true})});e.target.reset();message('بابەتی نوێ زیاد کرا.');loadPrices()}catch(x){message(x.message,false)}};
const serviceLabels={structurePerPanel:'ستراکچەری هەر پانێڵ',installationPerPanel:'دامەزراندنی هەر پانێڵ',solarCablePerMeter:'کێبڵی خۆر / مەتر',acCablePerMeter:'کێبڵی AC / مەتر',dcProtectionSingle:'DC Protection ـ یەک فەیز',dcProtection3ph:'DC Protection ـ سێ فەیز',acProtectionSingle:'AC Protection ـ یەک فەیز',acProtection3ph:'AC Protection ـ سێ فەیز',transportErbil:'گواستنەوەی هەولێر',transportOutside:'گواستنەوەی دەرەوەی هەولێر',otherElectricalUpTo16:'کاری کارەبایی تا ١٦ پانێڵ',otherElectricalAbove16:'کاری کارەبایی زیاتر لە ١٦ پانێڵ',batteryBusbarMinimum:'کەمترین باتری بۆ Busbar',batteryBusbarPrice:'نرخی Battery Busbar'};
let calcItems=[];
async function loadCalculator(){const d=await api('/admin/calculator');calcItems=d.items||[];$('#serviceFields').innerHTML=Object.entries(serviceLabels).map(([k,l])=>`<label>${l}<input type="number" min="0" step=".01" data-setting="${k}" value="${d.settings[k]??0}"></label>`).join('');renderCalculatorItems()}
function itemPayload(prefix,id=0){return {id,category:$(`#${prefix}Category`)?.value||$(`[data-field="category"][data-id="${id}"]`).value,quality:$(`#${prefix}Quality`)?.value||$(`[data-field="quality"][data-id="${id}"]`).value,mode:$(`#${prefix}Mode`)?.value||$(`[data-field="mode"][data-id="${id}"]`).value,name:$(`#${prefix}Name`)?.value||$(`[data-field="name"][data-id="${id}"]`).value,code:$(`#${prefix}Code`)?.value||$(`[data-field="code"][data-id="${id}"]`).value,price:+($(`#${prefix}Price`)?.value??$(`[data-field="price"][data-id="${id}"]`).value),warranty:$(`#${prefix}Warranty`)?.value||$(`[data-field="warranty"][data-id="${id}"]`).value,watts:+($(`#${prefix}Watts`)?.value??$(`[data-field="watts"][data-id="${id}"]`).value),kw:+($(`#${prefix}Kw`)?.value??$(`[data-field="kw"][data-id="${id}"]`).value),phase:$(`#${prefix}Phase`)?.value||$(`[data-field="phase"][data-id="${id}"]`).value,maxPanels:+($(`#${prefix}MaxPanels`)?.value??$(`[data-field="max_panels"][data-id="${id}"]`).value),ampsPerHour:+($(`#${prefix}Amps`)?.value??$(`[data-field="amps_per_hour"][data-id="${id}"]`).value),sortOrder:+($(`#${prefix}Sort`)?.value??$(`[data-field="sort_order"][data-id="${id}"]`).value),active:id?$(`[data-field="active"][data-id="${id}"]`).checked:true}}
function select(field,id,value,opts){return `<select data-field="${field}" data-id="${id}">${opts.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select>`}
function renderCalculatorItems(){const filter=$('#calcFilter').value,items=calcItems.filter(x=>filter==='all'||x.category===filter);$('#calcCount').textContent=`${items.length} بابەت`;$('#calculatorItems').innerHTML=items.map(x=>`<article class="catalog-card"><div class="catalog-head"><b>${esc(x.name)}</b><span>${x.category}</span></div><div class="form-grid calc-grid">${select('category',x.id,x.category,[['panel','پانێڵ'],['inverter','ئینڤێرتەر'],['battery','باتری']])}${select('quality',x.id,x.quality,[['high','بەرز'],['medium','ناوەند'],['standard','ئاسایی'],['common','هاوبەش']])}${select('mode',x.id,x.mode,[['both','هەردووکیان'],['easy','Easy'],['advanced','Advanced']])}<label>ناو<input data-field="name" data-id="${x.id}" value="${esc(x.name)}"></label><label>کۆد<input dir="ltr" data-field="code" data-id="${x.id}" value="${esc(x.code)}"></label><label>نرخ<input type="number" data-field="price" data-id="${x.id}" value="${x.price}"></label><label>گەرەنتی<input data-field="warranty" data-id="${x.id}" value="${esc(x.warranty)}"></label><label>وات<input type="number" data-field="watts" data-id="${x.id}" value="${x.watts}"></label><label>kW<input type="number" step=".1" data-field="kw" data-id="${x.id}" value="${x.kw}"></label>${select('phase',x.id,x.phase,[['single','Single Phase'],['3ph','3 Phase']])}<label>Max Panels<input type="number" data-field="max_panels" data-id="${x.id}" value="${x.max_panels}"></label><label>Amps/Hour<input type="number" data-field="amps_per_hour" data-id="${x.id}" value="${x.amps_per_hour}"></label><label>ڕیز<input type="number" data-field="sort_order" data-id="${x.id}" value="${x.sort_order}"></label><label class="active-label">چالاک<input class="check" type="checkbox" data-field="active" data-id="${x.id}" ${x.active?'checked':''}></label></div><div class="actions"><button data-save-calc="${x.id}">پاشەکەوت</button><button class="reject" data-delete-calc="${x.id}">سڕینەوە</button></div></article>`).join('');$$('[data-save-calc]').forEach(b=>b.onclick=()=>saveCalcItem(+b.dataset.saveCalc));$$('[data-delete-calc]').forEach(b=>b.onclick=()=>deleteCalcItem(+b.dataset.deleteCalc))}
async function saveCalcItem(id){const button=$(`[data-save-calc="${id}"]`),old=button?.textContent,payload=itemPayload('',id);if(button){button.disabled=true;button.textContent='پاشەکەوت دەکرێت...'}try{await api('/admin/calculator/item',{method:'POST',body:JSON.stringify(payload)});const index=calcItems.findIndex(x=>Number(x.id)===Number(id));if(index!==-1)calcItems[index]={...calcItems[index],category:payload.category,quality:payload.quality,mode:payload.mode,name:payload.name,code:payload.code,price:payload.price,warranty:payload.warranty,watts:payload.watts,kw:payload.kw,phase:payload.phase,max_panels:payload.maxPanels,amps_per_hour:payload.ampsPerHour,sort_order:payload.sortOrder,active:payload.active?1:0};renderCalculatorItems();message('گۆڕانکارییەکە پاشەکەوت کرا؛ دەتوانیت بەبێ Refresh دەستکاریی دیکە بکەیت.')}catch(e){message(e.message,false);if(button){button.disabled=false;button.textContent=old}}}
async function deleteCalcItem(id){if(!confirm('ئەم بابەتە لە کەلکولەیتەر بسڕدرێتەوە؟'))return;try{await api('/admin/calculator/item',{method:'DELETE',body:JSON.stringify({id})});message('بابەتەکە سڕایەوە.');loadCalculator()}catch(e){message(e.message,false)}}
$('#addCalcForm').onsubmit=async e=>{e.preventDefault();try{await api('/admin/calculator/item',{method:'POST',body:JSON.stringify(itemPayload('calc'))});e.target.reset();message('بابەتی نوێ زیاد کرا.');loadCalculator()}catch(x){message(x.message,false)}};
$('#saveServices').onclick=async()=>{const button=$('#saveServices'),old=button.textContent,settings={};$$('[data-setting]').forEach(x=>settings[x.dataset.setting]=+x.value);button.disabled=true;button.textContent='پاشەکەوت دەکرێت...';try{await api('/admin/calculator/settings',{method:'POST',body:JSON.stringify({settings})});button.disabled=false;button.textContent=old;message('هەموو نرخەکان پاشەکەوت کران؛ پێویست بە Refresh نییە.')}catch(e){message(e.message,false);button.disabled=false;button.textContent=old}};
$('#calcFilter').onchange=renderCalculatorItems;
function showPanel(){$('#adminLogin').classList.add('hidden');$('#adminPanel').classList.remove('hidden');loadApplications();loadPrices();loadCalculator()}
$('#adminLoginForm').onsubmit=async e=>{e.preventDefault();try{await api('/admin/login',{method:'POST',body:JSON.stringify({username:$('#adminUsername').value,password:$('#adminPassword').value})});showPanel()}catch(x){$('#adminLoginError').textContent=x.message}};
$('#adminLogout').onclick=async()=>{await api('/admin/logout',{method:'POST'});location.reload()};
$('#closeQr').onclick=()=>$('#qrDialog').close();$('#printQr').onclick=()=>window.print();$('#qrDialog').onclick=e=>{if(e.target===$('#qrDialog'))$('#qrDialog').close()};
$$('nav [data-view]').forEach(b=>b.onclick=()=>{$$('nav [data-view]').forEach(x=>x.classList.toggle('active',x===b));['applications','prices','calculator','analytics','announcements'].forEach(v=>$(`#${v}View`).classList.toggle('hidden',b.dataset.view!==v));if(b.dataset.view==='announcements')loadAnnouncements();if(b.dataset.view==='analytics')loadAnalytics()});
api('/admin/me').then(showPanel).catch(()=>{});

$$('[data-installer-status]').forEach(b=>b.onclick=()=>{installerStatus=b.dataset.installerStatus;$$('[data-installer-status]').forEach(x=>x.classList.toggle('active',x===b));filterApplications()});
let analyticsSequence=0;
async function loadAnalytics(){
 const sequence=++analyticsSequence;$('#analyticsMessage').textContent='ئامار بار دەکرێت...';
 try{const d=await api('/admin/analytics?days='+$('#analyticsDays').value);if(sequence!==analyticsSequence)return;
 const inspections=new Map(d.inspections.map(r=>[r.page,Number(r.requests)]));const totalRequests=d.inspections.reduce((n,r)=>n+Number(r.requests),0);
 $('#analyticsMetrics').innerHTML=[['سەردانکەری جیاواز',d.totals.visitors],['سەردانەکان',d.totals.sessions],['بینینی لاپەڕە',d.totals.views],['کلیکی واتسئاپ',d.totals.whatsapp],['داواکاری پشکنینی تۆمارکراو',totalRequests]].map(([label,n])=>`<div class="metric"><strong>${Number(n||0).toLocaleString()}</strong><span>${label}</span></div>`).join('');
 const pages=new Map(d.pages.map(p=>[p.page,p]));for(const page of inspections.keys())if(!pages.has(page))pages.set(page,{page});
 $('#analyticsPages').innerHTML=[...pages.values()].map(p=>`<tr><td><bdi>${esc(p.page)}</bdi></td><td>${Number(p.visitors||0)}</td><td>${Number(p.views||0)}</td><td>${Number(p.whatsapp||0)}</td><td>${inspections.get(p.page)||0}</td></tr>`).join('')||'<tr><td colspan="5">هێشتا داتا نییە.</td></tr>';
 $('#inspectionRequests').innerHTML=d.requests.map(r=>`<article class="app-card"><h3>${esc(r.name)}</h3><p><bdi>${esc(r.phone)}</bdi> · ${esc(r.city)}</p><p>${esc(r.note)}</p><small><bdi>${esc(r.created_at)} UTC</bdi> · ${esc(r.page)}</small></article>`).join('')||'<p>هێشتا داواکاری نییە.</p>';
 $('#analyticsMessage').textContent='نوێکرایەوە؛ ئاماری '+d.days+' ڕۆژی ڕابردوو.';
 }catch(e){if(sequence===analyticsSequence)$('#analyticsMessage').textContent=e.message}
}
$('#refreshAnalytics').onclick=loadAnalytics;$('#analyticsDays').onchange=loadAnalytics;

let adminAnnouncements=[];
async function loadAnnouncements(){const feedback=$('#announcementFeedback');try{const d=await api('/admin/announcements');adminAnnouncements=d.announcements||[];const list=$('#adminAnnouncements');list.replaceChildren();if(!adminAnnouncements.length){list.textContent='هێشتا ئاگادارکردنەوەیەک نییە.';return}for(const item of adminAnnouncements){const card=document.createElement('article');card.className='notice-card';const title=document.createElement('h3');title.textContent=item.title;const state=document.createElement('small');state.textContent=item.active?'چالاکە':'ناچالاکە';const text=document.createElement('p');text.textContent=item.message;const edit=document.createElement('button');edit.type='button';edit.textContent='دەستکاری / چالاککردن و ناچالاککردن';edit.onclick=()=>{$('#announcementId').value=item.id;$('#announcementTitle').value=item.title;$('#announcementMessage').value=item.message;$('#announcementKind').value=item.kind;$('#announcementActive').checked=!!item.active;$('#announcementTitle').focus();$('#announcementForm').scrollIntoView({behavior:'smooth',block:'start'})};card.append(state,title,text,edit);list.append(card)}}catch(e){feedback.textContent=e.message}}
$('#announcementNew').onclick=()=>{$('#announcementForm').reset();$('#announcementId').value='';$('#announcementFeedback').textContent='';$('#announcementTitle').focus()};
$('#announcementRefresh').onclick=loadAnnouncements;
$('#announcementForm').addEventListener('submit',async e=>{e.preventDefault();const button=$('#announcementSave');if(button.disabled)return;button.disabled=true;const feedback=$('#announcementFeedback');feedback.textContent='';try{const id=$('#announcementId').value;await api('/admin/announcements',{method:'POST',body:JSON.stringify({id:id?Number(id):null,title:$('#announcementTitle').value.trim(),message:$('#announcementMessage').value.trim(),kind:$('#announcementKind').value,active:$('#announcementActive').checked})});e.target.reset();$('#announcementId').value='';feedback.textContent='ئاگادارکردنەوەکە پاشەکەوت کرا.';await loadAnnouncements()}catch(x){feedback.textContent=x.message}finally{button.disabled=false}});
