'use strict';
const translations={
ku:{language:'زمان',readonly:'تەنها بینین',refresh:'نوێکردنەوە',companyNote:'ئەم سیستەمانە هەموویان لەلایەن کۆمپانیای ئەلو سۆلەر ئینێرجی دامەزراون.',title:'مۆنیتەری سیستەمە خۆرییەکان',subtitle:'دۆخی سیستەمەکان و بەرهەمی وزە بە شێوەیەکی پارێزراو پیشان دەدرێت.',connecting:'پەیوەندی دەکرێت…',connected:'پەیوەندی چالاکە',disconnected:'پەیوەندی نییە',summaryLabel:'پوختەی سیستەمەکان',totalSystems:'هەموو سیستەمەکان',online:'چالاک',generationNow:'بەرهەمی ئێستا',consumptionNow:'بەکارهێنانی ئێستا',systems:'سیستەمەکان',privacyNote:'ناوی کڕیار تەنها بە دوو پیتی یەکەم دەردەکەوێت.',search:'گەڕان بە ناوی پارێزراو…',notFound:'هیچ سیستەمێک نەدۆزرایەوە',changeSearch:'گەڕانەکەت بگۆڕە یان دواتر هەوڵ بدەرەوە.',connectionFailed:'پەیوەندی بە مۆنیتەرەکە نەکرا',footer:'مۆنیتەرینگی گشتی تەنها بۆ بینین',customer:'کڕیار',generation:'بەرهەمهێنان',consumption:'بەکارهێنان',battery:'باتری',grid:'تۆڕ',lastUpdate:'دوا نوێکردنەوە',onlineStatus:'چالاک',offlineStatus:'ناچالاک',secrets:'هێشتا نهێنییەکانی Deye لە Cloudflare ڕێکنەخراون.',connectionError:'هەڵەی پەیوەندی'},
ar:{language:'اللغة',readonly:'للعرض فقط',refresh:'تحديث',companyNote:'تم تركيب جميع هذه الأنظمة من قبل شركة ألو للطاقة الشمسية.',title:'مراقبة أنظمة الطاقة الشمسية',subtitle:'تُعرض حالة الأنظمة وإنتاج الطاقة بصورة آمنة ومباشرة.',connecting:'جارٍ الاتصال…',connected:'الاتصال نشط',disconnected:'لا يوجد اتصال',summaryLabel:'ملخص الأنظمة',totalSystems:'جميع الأنظمة',online:'متصل',generationNow:'الإنتاج الحالي',consumptionNow:'الاستهلاك الحالي',systems:'الأنظمة',privacyNote:'يظهر أول حرفين فقط من اسم العميل حفاظاً على الخصوصية.',search:'البحث بالاسم المحمي…',notFound:'لم يتم العثور على أي نظام',changeSearch:'غيّر البحث أو حاول مرة أخرى لاحقاً.',connectionFailed:'تعذر الاتصال بالمراقبة',footer:'مراقبة عامة للعرض فقط',customer:'عميل',generation:'الإنتاج',consumption:'الاستهلاك',battery:'البطارية',grid:'الشبكة',lastUpdate:'آخر تحديث',onlineStatus:'متصل',offlineStatus:'غير متصل',secrets:'لم يتم إعداد بيانات Deye السرية في Cloudflare بعد.',connectionError:'خطأ في الاتصال'},
en:{language:'Language',readonly:'View only',refresh:'Refresh',companyNote:'All these systems were installed by Alo Solar Energy Company.',title:'Solar System Monitoring',subtitle:'System status and energy production are displayed securely in real time.',connecting:'Connecting…',connected:'Connection active',disconnected:'No connection',summaryLabel:'System summary',totalSystems:'All systems',online:'Online',generationNow:'Current generation',consumptionNow:'Current consumption',systems:'Systems',privacyNote:'Only the first two letters of each customer name are displayed for privacy.',search:'Search by protected name…',notFound:'No systems found',changeSearch:'Change your search or try again later.',connectionFailed:'Could not connect to the monitor',footer:'Public read-only solar monitoring',customer:'Customer',generation:'Generation',consumption:'Consumption',battery:'Battery',grid:'Grid',lastUpdate:'Last update',onlineStatus:'Online',offlineStatus:'Offline',secrets:'Deye secrets have not yet been configured in Cloudflare.',connectionError:'Connection error'}};
const els={grid:document.getElementById('stationGrid'),empty:document.getElementById('emptyState'),error:document.getElementById('errorState'),errorMessage:document.getElementById('errorMessage'),refresh:document.getElementById('refreshBtn'),search:document.getElementById('searchInput'),dot:document.getElementById('syncDot'),sync:document.getElementById('syncText'),updated:document.getElementById('updatedAt'),language:document.getElementById('languageSelect')};
let stations=[],lang=localStorage.getItem('aloMonitorLanguage')||'ku',lastUpdated=null,lastError='';
const extraTranslations={
ku:{backHome:'گەڕانەوە بۆ سەرەکی',staleData:'داتاکە نوێ نییە؛ کۆتا نوێکردنەوە زیاتر لە ١٥ خولەک پێش ئێستا بووە.',todayEnergy:'بەرهەمی ئەمڕۆ',co2Reduced:'کەمکردنەوەی CO₂ ئەمڕۆ',co2Estimate:'هەژمارێکی نزیکەیی',erbilWeather:'کەشوهەوای هەولێر',weatherLoading:'داتا وەردەگیرێت…',weatherUnavailable:'داتای کەشوهەوا بەردەست نییە',clear:'ئاسمان ساماڵە',cloudy:'هەوراوی',rainy:'باراناوی',support:'پشتیوانی',whatsappLabel:'پەیوەندی بە Alo Solar لە WhatsApp',solarSource:'خۆر',batterySource:'باتری',gridSource:'تۆڕ',generatorSource:'جەنەریتەر'},
ar:{backHome:'العودة إلى الرئيسية',staleData:'البيانات ليست حديثة؛ آخر تحديث كان قبل أكثر من 15 دقيقة.',todayEnergy:'إنتاج اليوم',co2Reduced:'خفض CO₂ اليوم',co2Estimate:'حساب تقديري',erbilWeather:'طقس أربيل',weatherLoading:'جارٍ جلب البيانات…',weatherUnavailable:'بيانات الطقس غير متاحة',clear:'سماء صافية',cloudy:'غائم',rainy:'ممطر',support:'الدعم',whatsappLabel:'تواصل مع ألو سولار عبر واتساب',solarSource:'الشمس',batterySource:'البطارية',gridSource:'الشبكة',generatorSource:'المولد'},
en:{backHome:'Back to Home',staleData:'Data may be outdated; the last update was more than 15 minutes ago.',todayEnergy:'Today’s production',co2Reduced:'CO₂ reduced today',co2Estimate:'Estimated value',erbilWeather:'Erbil weather',weatherLoading:'Loading weather…',weatherUnavailable:'Weather data unavailable',clear:'Clear sky',cloudy:'Cloudy',rainy:'Rainy',support:'Support',whatsappLabel:'Contact Alo Solar on WhatsApp',solarSource:'Solar',batterySource:'Battery',gridSource:'Grid',generatorSource:'Generator'}};
const tr=key=>extraTranslations[lang]?.[key]||translations[lang][key]||translations.en[key]||key;
const num=value=>Number.isFinite(Number(value))?Number(value):0;
const power=value=>`${(num(value)/1000).toFixed(2)} kW`;
const safeName=value=>{const clean=String(value||tr('customer')).trim().replace(/[<>]/g,'');return clean.endsWith('******')?clean:`${Array.from(clean).slice(0,2).join('')}******`;};
const time=value=>{if(!value)return '—';const date=new Date(typeof value==='number'&&value<1e12?value*1000:value);return Number.isNaN(date.getTime())?'—':date.toLocaleString(lang==='ku'?'ku-IQ':lang==='ar'?'ar-IQ':'en-US');};
const text=(tag,className,value)=>{const node=document.createElement(tag);if(className)node.className=className;node.textContent=value;return node;};
function metric(label,value,className=''){const box=text('div',`metric ${className}`,'');box.append(text('span','',label),text('strong','',value));return box;}
function card(s){const article=text('article','station',''),head=text('div','station-head',''),nameWrap=document.createElement('div');nameWrap.append(text('h3','customer',safeName(s.customerName)),text('div','capacity',`${num(s.installedCapacity).toFixed(1)} kWp`));const isOnline=s.status==='online';head.append(nameWrap,text('span',`status ${isOnline?'online':'offline'}`,`● ${isOnline?tr('onlineStatus'):tr('offlineStatus')}`));const metrics=text('div','metrics','');metrics.append(metric(tr('generation'),power(s.generationPower),'pv'),metric(tr('consumption'),power(s.consumptionPower)),metric(tr('battery'),`${num(s.batterySOC).toFixed(0)}%`,'battery'),metric(tr('grid'),power(s.gridPower)));const foot=text('div','station-time','');foot.append(text('span','',tr('lastUpdate')),text('span','',time(s.lastUpdateTime)));article.append(head,metrics,foot);return article;}
function render(){const q=els.search.value.trim().toLocaleLowerCase();const filtered=stations.filter(s=>safeName(s.customerName).toLocaleLowerCase().includes(q));els.grid.replaceChildren(...filtered.map(card));els.empty.hidden=filtered.length!==0||!stations.length;}
function summary(){document.getElementById('totalStations').textContent=stations.length;document.getElementById('onlineStations').textContent=stations.filter(s=>s.status==='online').length;document.getElementById('totalGeneration').textContent=power(stations.reduce((a,s)=>a+num(s.generationPower),0));document.getElementById('totalConsumption').textContent=power(stations.reduce((a,s)=>a+num(s.consumptionPower),0));}
const extraEls={stale:document.getElementById('staleWarning'),today:document.getElementById('todayEnergy'),co2:document.getElementById('co2Reduced'),weatherValue:document.getElementById('weatherValue'),weatherText:document.getElementById('weatherText'),weatherIcon:document.getElementById('weatherIcon')};
const firstNumber=(object,keys)=>{for(const key of keys){const value=Number(object?.[key]);if(Number.isFinite(value))return value;}return 0;};
const stationToday=s=>firstNumber(s,['todayEnergy','generationToday','dailyEnergy','dayEnergy','etoday','eToday','todayProduction']);
const originalCard=card;
card=function(s){const article=originalCard(s),flow=text('div','power-flow','');const sources=[['☀',tr('solarSource'),num(s.generationPower)>0],['▣',tr('batterySource'),num(s.batteryPower)!==0||num(s.batterySOC)>0],['⚡',tr('gridSource'),num(s.gridPower)!==0],['G',tr('generatorSource'),num(s.generatorPower)>0]];sources.forEach(([icon,label,active])=>{const item=text('span',active?'active':'','');item.append(text('i','',icon),text('b','',label));flow.append(item);});article.insertBefore(flow,article.querySelector('.station-time'));return article;};
const originalSummary=summary;
summary=function(){originalSummary();};
function updateStale(){if(!lastUpdated){extraEls.stale.hidden=true;return;}const date=new Date(lastUpdated);extraEls.stale.hidden=Number.isNaN(date.getTime())||Date.now()-date.getTime()<=900000;}
function weatherKind(code){if(code>=51)return ['🌧',tr('rainy')];if(code>=1)return ['☁',tr('cloudy')];return ['☀',tr('clear')];}
async function loadWeather(){try{const response=await fetch('https://api.open-meteo.com/v1/forecast?latitude=36.19&longitude=44.01&current=temperature_2m,weather_code&timezone=Asia%2FBaghdad',{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json(),current=data.current||{},kind=weatherKind(Number(current.weather_code));extraEls.weatherIcon.textContent=kind[0];extraEls.weatherValue.textContent=Number.isFinite(Number(current.temperature_2m))?`${Number(current.temperature_2m).toFixed(0)}°C`:'—';extraEls.weatherText.textContent=kind[1];}catch{extraEls.weatherIcon.textContent='◌';extraEls.weatherValue.textContent='—';extraEls.weatherText.textContent=tr('weatherUnavailable');}}
function applyLanguage(next){lang=translations[next]?next:'ku';localStorage.setItem('aloMonitorLanguage',lang);els.language.value=lang;document.documentElement.lang=lang;document.documentElement.dir=lang==='en'?'ltr':'rtl';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=tr(el.dataset.i18nPlaceholder));document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',tr(el.dataset.i18nAria)));document.title=`Alo Solar Energy | ${tr('title')}`;if(lastUpdated)els.updated.textContent=time(lastUpdated);if(lastError)els.errorMessage.textContent=lastError==='secrets'?tr('secrets'):`${tr('connectionError')}: ${lastError}`;render();}
async function load(){els.refresh.disabled=true;els.error.hidden=true;lastError='';els.sync.textContent=tr('connecting');els.dot.className='dot';try{const response=await fetch('/api/deye/dashboard',{headers:{accept:'application/json'},cache:'no-store'});if(!response.ok){lastError=response.status===503?'secrets':String(response.status);throw new Error(lastError);}const data=await response.json();stations=Array.isArray(data.stations)?data.stations:[];summary();render();els.dot.className='dot ok';els.sync.textContent=tr('connected');lastUpdated=data.updatedAt||Date.now();els.updated.textContent=time(lastUpdated);updateStale();}catch(error){stations=[];summary();render();els.dot.className='dot bad';els.sync.textContent=tr('disconnected');lastError=lastError||error.message;els.errorMessage.textContent=lastError==='secrets'?tr('secrets'):`${tr('connectionError')}: ${lastError}`;els.error.hidden=false;}finally{els.refresh.disabled=false;}}
els.refresh.addEventListener('click',load);els.search.addEventListener('input',render);els.language.addEventListener('change',event=>{applyLanguage(event.target.value);loadWeather();});applyLanguage(lang);load();loadWeather();setInterval(load,60000);setInterval(updateStale,60000);setInterval(loadWeather,900000);
