const P='assets/products/',D='datasheets/';
const products=[
{type:'panel',name:'LONGi Hi-MO X10 Anti-Dust Pro',model:'LR8-66HVDF 640-670M',img:'longi-x10.jpg',pdf:'Anti-Dust-LR8-66HVDF-640-670M-Anti-dust-Pro.pdf.pdf',w:'15 years product / 30 years power',s:[['Power','640-670 W'],['Efficiency','Up to 24.8%'],['Cell','Back Contact, 132 cells'],['Protection','IP68 junction box'],['Weight','32.6 kg'],['Size','2382 × 1134 mm']]},
{type:'panel',name:'Power Solid N-Type Bifacial',model:'PS620W#PVBN',img:'powersolid-620.jpg',pdf:'PS620WPVBN.pdf',w:'15 years (Alo product listing)',s:[['Power','620 W'],['Technology','N-Type Bifacial'],['Cells','144 half-cells'],['Load','2400 / 5400 Pa'],['Weight','33.5 kg'],['Size','2382 × 1134 mm']]},
{type:'inverter',name:'Deye Single-Phase Hybrid',model:'SUN-3/3.6/4/4.6/5/6K-SG06LP1',img:'deye-sp-3-6.jpg',pdf:'BDatasheetSUN-3-6K-SG06LP1-EU-CM220260911en.pdf',w:'5 years',s:[['Output','3-6 kW'],['Battery','40-60 V'],['PV voltage','Max 500 V'],['Efficiency','97.6%'],['Protection','IP65'],['Interface','WiFi, RS485, CAN']]},
{type:'inverter',name:'Deye Single-Phase Hybrid',model:'SUN-7/7.6/8/10K-SG05LP1',img:'deye-sp-7-10.jpg',pdf:'BDatasheetSUN-7-10K-SG05LP1-EU-SM220260911en.pdf',w:'5 years',s:[['Output','7-10 kW'],['Battery','40-60 V'],['PV voltage','Max 500 V'],['Efficiency','97.6%'],['Protection','IP65'],['Parallel','Up to 16 units']]},
{type:'inverter',name:'Deye Single-Phase Hybrid',model:'SUN-7.6/8/10/12K-SG02LP1',img:'deye-sp-7-12.jpg',pdf:'BDatasheetSUN-76-12K-SG02LP1-EU-AM220260911en.pdf',w:'5 years',s:[['Output','7.6-12 kW'],['Battery','40-60 V'],['PV voltage','Max 500 V'],['Efficiency','97.6%'],['Protection','IP65'],['Weight','35.6 kg']]},
{type:'inverter',name:'Deye Single-Phase Hybrid',model:'SUN-12/14/16K-SG01LP1',img:'deye-sp-12-16.jpg',pdf:'bdatasheet_sun-12-16kk-sg01lp1-eu_20260706_en.pdf',w:'5 years',s:[['Output','12-16 kW'],['Battery','40-60 V'],['MPPT','3 trackers'],['Efficiency','97.6%'],['Protection','IP65'],['Weight','52 kg']]},
{type:'inverter',name:'Deye Three-Phase Hybrid',model:'SUN-3/4/5/6/8/10/12K-SG05LP3',img:'deye-3p-3-12.jpg',pdf:'BDatasheetSUN-3-12K-SG05LP3-EU-SM220260911en.pdf',w:'5 years',s:[['Output','3-12 kW'],['Battery','40-60 V'],['PV voltage','Max 800 V'],['Efficiency','97.6%'],['Protection','IP65'],['Output','100% unbalanced']]},
{type:'inverter',name:'Deye Three-Phase Hybrid',model:'SUN-14/15/16/18/20K-SG05LP3',img:'deye-3p-14-20.jpg',pdf:'BDatasheetSUN-14-20K-SG05LP3-EU-SM220260911en.pdf',w:'5 years',s:[['Output','14-20 kW'],['Battery','40-60 V'],['PV voltage','Max 800 V'],['Efficiency','97.6%'],['Protection','IP65'],['Charge current','Up to 350 A']]},
{type:'inverter',name:'Medal Power Hybrid Inverter',model:'MPHi-6KW#48VPVSE',img:'medal-6.jpg',pdf:'MPHi-6KW48VPVSE_1-1.pdf',w:'4 years',s:[['Output','6 kW'],['Battery','40-60 V'],['PV usable','9 kW'],['PV voltage','Max 500 V'],['Protection','IP54'],['Parallel','Up to 12 units']]},
{type:'inverter',name:'Bryyzee Hybrid Inverter',model:'BRHi-6.2KW#48VPVT',img:'bryyzee-6.jpg',pdf:'BRHi-6.2KW48VPVT.pdf',w:'2 years (Alo product listing)',s:[['Output','6.2 kW'],['Battery','48 V'],['PV voltage','Max 500 V'],['MPPT range','60-500 V'],['DC/AC efficiency','98%'],['Protection','IP21']]},
{type:'battery',name:'Pylontech Fidus Battery Plus',model:'FB-L-16 / FB-L-16-Pro',img:'pylontech-fidus.jpg',pdf:'Pylon-tech-16kwh.pdf',w:'10 years (Alo product listing)',s:[['Energy','16.076 kWh'],['Voltage','51.2 V'],['Usable capacity','16.076 kWh'],['Cycle life','8000 cycles'],['Protection','IP65'],['Current','200 A continuous']]},
{type:'battery',name:'Hoymiles Low Voltage Battery',model:'LB-16D-G3',img:'hoymiles-16.jpg',pdf:'Hoymiles-16-kw-battery-.pdf',w:'5 years',s:[['Energy','16.08 kWh'],['Capacity','314 Ah'],['Voltage','51.2 V'],['Cycle life','8000 cycles'],['Protection','IP65'],['Weight','110 kg']]},
{type:'battery',name:'EENOVANCE MANA-M Series',model:'MANA 5.1 / 10.4 / 16.0 / 20.5',img:'mana-m.jpg',pdf:'EENOVANCE_MANA-M-Series_Datasheet3.pdf',w:'5 years',s:[['Energy','5.1-20.5 kWh'],['Chemistry','LiFePO4'],['Installation','Floor standing'],['Communication','CAN / RS485'],['Use','Residential ESS'],['Design','Modular range']]},
{type:'battery',name:'3Watt Lithium Battery',model:'WT-5121000-LT',img:'3watt-100ah.jpg',pdf:'WT-5121000-LT.pdf',w:'5 years (Alo product listing)',s:[['Energy','5.12 kWh'],['Capacity','100 Ah'],['Voltage','51.2 V'],['Cycle life','≥4000 cycles'],['Current','75 A discharge'],['Weight','Approx. 48 kg']]}
];
const tx={
ku:{home:'سەرەتا',eyebrow:'بەرهەمە ڕەسەنەکان',title:'داتاشیتی ئەو بەرهەمانەی کە کۆمپانیای ئەلو سۆلەر ئینێرجی بەکاریان دەهێنێت',intro:'پانێڵ، ئینڤێرتەر و باتری بە مواسەفاتی ڕوون، گەرەنتی و داتاشیتی فەرمی.',all:'هەمووی',panels:'پانێڵەکان',inverters:'ئینڤێرتەرەکان',batteries:'باترییەکان',noteTitle:'تێبینی گرنگ',note:'مواسەفاتەکان لە داتاشیتی فەرمیی بەرهەمهێنەر وەرگیراون. گەرەنتی کۆتایی بە مۆدێل، بازاڕ و مەرجەکانی بەرهەمهێنەر پەیوەستە.',ask:'پرسیار بکە',panel:'پانێڵی خۆری',inverter:'ئینڤێرتەر',battery:'باتری لیتیۆم',warranty:'گەرەنتی',download:'دابەزاندنی Datasheet',count:n=>`${n} بەرهەم`},
ar:{home:'الرئيسية',eyebrow:'منتجات أصلية',title:'البيانات الفنية للمنتجات التي تستخدمها شركة ألو سولار إنرجي',intro:'ألواح وإنفرترات وبطاريات بمواصفات واضحة وضمان وبيانات رسمية.',all:'الكل',panels:'الألواح',inverters:'الإنفرترات',batteries:'البطاريات',noteTitle:'ملاحظة مهمة',note:'المواصفات مأخوذة من بيانات الشركة المصنعة. يعتمد الضمان النهائي على الموديل والسوق وشروط الشركة المصنعة.',ask:'اسألنا',panel:'لوح شمسي',inverter:'إنفرتر',battery:'بطارية ليثيوم',warranty:'الضمان',download:'تحميل Datasheet',count:n=>`${n} منتج`},
en:{home:'Home',eyebrow:'GENUINE PRODUCTS',title:'Datasheets for Products Used by Alo Solar Energy',intro:'Panels, inverters and batteries with clear specifications, warranty information and official datasheets.',all:'All',panels:'Panels',inverters:'Inverters',batteries:'Batteries',noteTitle:'Important note',note:'Specifications are taken from official manufacturer datasheets. Final warranty depends on model, market and manufacturer terms.',ask:'Ask us',panel:'Solar panel',inverter:'Inverter',battery:'Lithium battery',warranty:'Warranty',download:'Download Datasheet',count:n=>`${n} products`}}
let lang=localStorage.getItem('aloLanguage')||'ku',filter='all';
function render(){const t=tx[lang];document.documentElement.lang=lang;document.documentElement.dir=lang==='en'?'ltr':'rtl';document.querySelectorAll('[data-t]').forEach(e=>{if(t[e.dataset.t])e.textContent=t[e.dataset.t]});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));const shown=products.filter(p=>filter==='all'||p.type===filter);document.getElementById('count').textContent=t.count(shown.length);document.getElementById('productGrid').innerHTML=shown.map(p=>`<article class="card"><div class="photo"><img src="${P+p.img}" alt="${p.name}" loading="lazy"></div><div class="body"><span class="type">${t[p.type]}</span><h2>${p.name}</h2><div class="model">${p.model}</div><div class="specs">${p.s.map(x=>`<div class="spec"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div><div class="warranty">✓ ${t.warranty}: ${p.w}</div><a class="download" href="${D+p.pdf}" target="_blank" rel="noopener">↧ ${t.download}</a></div></article>`).join('')}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;localStorage.setItem('aloLanguage',lang);render()}));document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()}));render();
