PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS installers (id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,phone TEXT NOT NULL UNIQUE,business TEXT,city TEXT,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','disabled')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,approved_at TEXT,verification_code TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS sessions (id INTEGER PRIMARY KEY AUTOINCREMENT,token_hash TEXT NOT NULL UNIQUE,user_id INTEGER,role TEXT NOT NULL CHECK(role IN ('installer','admin')),expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES installers(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash,role,expires_at);
CREATE TABLE IF NOT EXISTS login_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT,key TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_attempts_key ON login_attempts(key,created_at);
CREATE TABLE IF NOT EXISTS installer_products (id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,name TEXT NOT NULL,spec TEXT,retail_price REAL NOT NULL DEFAULT 0,trade_price REAL NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO installer_products(id,type,name,spec,retail_price,trade_price,sort_order) VALUES
(1,'panel','Longi Hi-MO X10 650W Anti-Dust Pro','15Y Warranty · N-Type HPBC 2.0',0,0,10),(2,'panel','Power Solid 620W','15Y Warranty · Bifacial PV Module',0,0,20),(3,'inverter','Deye Hybrid Inverter 20kW 3PH','5Y Warranty · Three Phase',2500,2300,30),(4,'inverter','Bryyzee Hybrid Inverter 6.2kW','2Y Warranty · Single Phase',335,308,40),(5,'inverter','Viva Hybrid Inverter 11kW','2Y Warranty · Single Phase',775,713,50),(6,'battery','3Watt Lithium Battery 100Ah 51.2V','5Y Warranty · LiFePO4',650,598,60),(7,'battery','Viva Lithium Battery 314Ah 51.2V','5Y Warranty · LiFePO4',1590,1463,70),(8,'battery','EVE Lithium Battery 314Ah 51.2V','5Y Warranty · LiFePO4',1620,1490,80),(9,'structure','Panel Structure','Price for each solar panel',45,41.4,90),(10,'electrical','DC Protection — Single Phase','Complete protection board',75,69,100),(11,'electrical','AC Protection — Three Phase','Complete protection board',100,92,110),(12,'cable','Solar Cable 6mm','Price per meter',1.25,1.15,120);
CREATE TABLE IF NOT EXISTS calculator_items (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,category TEXT NOT NULL,quality TEXT NOT NULL DEFAULT 'common',mode TEXT NOT NULL DEFAULT 'both',name TEXT NOT NULL,price REAL NOT NULL DEFAULT 0,warranty TEXT,watts REAL NOT NULL DEFAULT 0,kw REAL NOT NULL DEFAULT 0,phase TEXT NOT NULL DEFAULT 'single',max_panels INTEGER NOT NULL DEFAULT 0,amps_per_hour REAL NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS calculator_settings (key TEXT PRIMARY KEY,value REAL NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
